### ISSUE TITLE
Missing lexical expression

### ISSUE THREAD

**Issue by jkiddo** [bartdecu/fhirfederator#29]
When issuing `/Patient?identifier1%7C2&_revinclude=Coverage:subscriber` the following error pops up:

`HAPI-0389: Failed to call access method: java.lang.NullPointerException: Cannot invoke \"ca.uhn.fhir.federator.FhirUrlParser$DContext.getText()\" because the return value of \"ca.uhn.fhir.federator.FhirUrlParser$PContext.d()\" is null"
  } ]
}`

**Comment by bartdecu** [comment]
When I look at the search statement:
Patient?identifier1|2&_revinclude=Coverage:subscriber

I see that the statement is not valid, because identifier1|2 is an unknown parameter. The solution according to the standard can be found here: https://www.hl7.org/fhir/search.html#errors

Todo: 
1) catch parser error, and locate the problem (find out it happens on the level of the parameter)
2) check the Prefer header
3) take appropriate action, i.e. ignore the parameter, or send an error, depending on 2

**Comment by jkiddo** [comment]
🤦‍♂️- I totally missed the missing '='

**Comment by bartdecu** [comment]
@jkiddo No, your remark was justified, the error should be properly handled.
